# Generated by Django 4.2.4 on 2023-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('caddress', models.CharField(max_length=100)),
                ('cimage', models.ImageField(default='null.jpg', upload_to='data')),
                ('cplace', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=254)),
                ('cpassword', models.CharField(max_length=100)),
                ('checkindate', models.DateField()),
                ('checkoutdate', models.DateField()),
                ('rooms', models.IntegerField()),
            ],
        ),
    ]
