# Generated by Django 4.2.4 on 2023-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('haddress', models.CharField(max_length=100)),
                ('himage', models.ImageField(default='null.jpg', upload_to='data')),
                ('hprice', models.IntegerField()),
                ('hdescription', models.CharField(max_length=100)),
                ('hstate', models.CharField(max_length=100)),
                ('hcity', models.CharField(max_length=100)),
                ('hpin', models.IntegerField()),
                ('hemail', models.EmailField(max_length=254)),
                ('hpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
